# Generated by Django 4.2.9 on 2024-08-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gl_level_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl_level_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl_level_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('gl_level_1', models.ForeignKey(blank=True, db_column='gl_level_1_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invoice.gllevel1')),
                ('gl_level_2', models.ForeignKey(blank=True, db_column='gl_level_2_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invoice.gllevel2')),
                ('gl_level_3', models.ForeignKey(blank=True, db_column='gl_level_3_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invoice.gllevel3')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
