# Generated by Django 4.2.9 on 2025-03-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
