# Generated by Django 4.2.8 on 2024-01-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_training',
            old_name='label',
            new_name='type',
        ),
    ]
