# Generated by Django 4.2.9 on 2024-09-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0004_processedinvoice_vendor_short_name'),
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCollectionCycle',
            fields=[
                ('cycle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_collection_cycles',
            },
        ),
        migrations.CreateModel(
            name='InventoryQueueItem',
            fields=[
                ('inventory_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_result', models.JSONField(blank=True, null=True)),
                ('gl_level_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_queue_items', to='invoice.gllevel1')),
                ('gl_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_queue_items', to='invoice.gllevel2')),
                ('gl_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_queue_items', to='invoice.gllevel3')),
                ('inventory_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventorycollectioncycle')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_queue_items',
            },
        ),
    ]
