# Generated by Django 4.2.9 on 2025-03-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_delete_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryqueueitem',
            name='image',
        ),
    ]
