# Generated by Django 4.2.9 on 2025-03-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_remove_inventoryqueueitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryqueueitem',
            name='gl_level_1',
        ),
        migrations.RemoveField(
            model_name='inventoryqueueitem',
            name='gl_level_2',
        ),
        migrations.RemoveField(
            model_name='inventoryqueueitem',
            name='gl_level_3',
        ),
        migrations.RemoveField(
            model_name='inventoryqueueitem',
            name='product_name',
        ),
    ]
