# Generated by Django 4.2.9 on 2025-03-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_remove_inventoryqueueitem_gl_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycollectioncycle',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorycollectioncycle',
            name='cycle_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorycollectioncycle',
            name='cycle_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
