# Generated by Django 4.2.9 on 2024-03-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_weightreading_alter_gllevel1_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeightReading',
        ),
    ]
