# Generated by Django 4.2.9 on 2024-10-05 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedGL',
            fields=[
                ('consolidated_gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl1_id', models.IntegerField(blank=True, null=True)),
                ('gl1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl1_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gl2_id', models.IntegerField(blank=True, null=True)),
                ('gl2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl2_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gl3_id', models.IntegerField(blank=True, null=True)),
                ('gl3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl3_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'consolidated_gl',
            },
        ),
        migrations.CreateModel(
            name='GLLevel1',
            fields=[
                ('gl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl1_name', models.CharField(max_length=100)),
                ('gl1_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'gl_level_1',
            },
        ),
        migrations.CreateModel(
            name='GLLevel2',
            fields=[
                ('gl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl2_name', models.CharField(max_length=100)),
                ('gl2_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'gl_level_2',
            },
        ),
        migrations.CreateModel(
            name='GLLevel3',
            fields=[
                ('gl3_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl3_name', models.CharField(max_length=100)),
                ('gl3_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'gl_level_3',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'in_invoice_processing_upload',
            },
        ),
        migrations.CreateModel(
            name='ProcessedInvoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_invoice_processing_id', models.IntegerField()),
                ('s3_object_key', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('invoice_receipt_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('batched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_invoice_processed',
            },
        ),
        migrations.CreateModel(
            name='ProcessedLineItem',
            fields=[
                ('line_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_invoice_processing_id', models.IntegerField(blank=True, null=True)),
                ('s3_object_key', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_receipt_id', models.TextField(blank=True, null=True)),
                ('expense_document_index', models.IntegerField(blank=True, null=True)),
                ('line_item_index', models.IntegerField(blank=True, null=True)),
                ('product_code', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('pack', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_row', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_line_item_processed',
            },
        ),
        migrations.CreateModel(
            name='ProcessedProduct',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.TextField()),
                ('item_description', models.TextField()),
                ('brand', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'out_product_processed',
            },
        ),
        migrations.CreateModel(
            name='ProcessedVendor',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('most_recent_in_invoice_processing_id', models.IntegerField(blank=True, null=True)),
                ('most_recent_s3_object_key', models.CharField(blank=True, max_length=255, null=True)),
                ('most_recent_upload_date', models.DateTimeField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_street', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_city', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_state', models.CharField(blank=True, max_length=2, null=True)),
                ('vendor_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_block', models.TextField(blank=True, null=True)),
                ('vendor_remit_address', models.CharField(blank=True, max_length=255, null=True)),
                ('remit_to_street', models.CharField(blank=True, max_length=255, null=True)),
                ('remit_to_city', models.CharField(blank=True, max_length=255, null=True)),
                ('remit_to_state', models.CharField(blank=True, max_length=2, null=True)),
                ('remit_to_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('remit_to_address_block', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('batched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_vendor_processed',
            },
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enhanced_details', models.TextField(blank=True, null=True)),
                ('storage_guidelines', models.TextField(blank=True, null=True)),
                ('handling_instructions', models.TextField(blank=True, null=True)),
                ('allergens', models.TextField(blank=True, null=True)),
                ('nutritional_info', models.TextField(blank=True, null=True)),
                ('regulatory_compliance', models.TextField(blank=True, null=True)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_product_classification',
            },
        ),
        migrations.AddConstraint(
            model_name='productclassification',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_productclassification_name_lower'),
        ),
        migrations.AlterUniqueTogether(
            name='processedvendor',
            unique_together={('vendor_short_name', 'account_number')},
        ),
        migrations.AddField(
            model_name='processedproduct',
            name='classification',
            field=models.ForeignKey(blank=True, db_column='classification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.productclassification'),
        ),
        migrations.AddField(
            model_name='processedlineitem',
            name='gl3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.gllevel3'),
        ),
        migrations.AddField(
            model_name='processedlineitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.processedinvoice'),
        ),
        migrations.AddField(
            model_name='processedlineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.processedproduct'),
        ),
        migrations.AddField(
            model_name='processedinvoice',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.processedvendor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gllevel3',
            name='gl2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_level_3', to='invoice.gllevel2'),
        ),
        migrations.AddField(
            model_name='gllevel2',
            name='gl1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_level_2', to='invoice.gllevel1'),
        ),
        migrations.AlterUniqueTogether(
            name='consolidatedgl',
            unique_together={('gl3_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='processedproduct',
            unique_together={('product_code', 'item_description')},
        ),
        migrations.AddIndex(
            model_name='processedlineitem',
            index=models.Index(fields=['invoice'], name='idx_invoice'),
        ),
        migrations.AddIndex(
            model_name='processedlineitem',
            index=models.Index(fields=['product'], name='idx_product'),
        ),
        migrations.AddIndex(
            model_name='processedlineitem',
            index=models.Index(fields=['gl3'], name='idx_gl3'),
        ),
        migrations.AlterUniqueTogether(
            name='gllevel3',
            unique_together={('gl2', 'gl3_code')},
        ),
        migrations.AlterUniqueTogether(
            name='gllevel2',
            unique_together={('gl1', 'gl2_code')},
        ),
    ]
