# Generated by Django 4.2.9 on 2024-08-06 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GLLevel1',
            fields=[
                ('gl1_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl1_name', models.CharField(max_length=100)),
                ('gl1_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'gl_level_1',
            },
        ),
        migrations.CreateModel(
            name='GLLevel2',
            fields=[
                ('gl2_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl2_name', models.CharField(max_length=100)),
                ('gl2_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gl1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_level_2', to='invoice.gllevel1')),
            ],
            options={
                'db_table': 'gl_level_2',
                'unique_together': {('gl1', 'gl2_code')},
            },
        ),
        migrations.CreateModel(
            name='ProcessedInvoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_invoice_processing_id', models.IntegerField()),
                ('s3_object_key', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('account_number', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('invoice_receipt_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_id', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('batched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_invoice_processed',
            },
        ),
        migrations.CreateModel(
            name='ProcessedLineItem',
            fields=[
                ('line_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_invoice_processing_id', models.IntegerField(blank=True, null=True)),
                ('s3_object_key', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('invoice_receipt_id', models.TextField(blank=True, null=True)),
                ('expense_document_index', models.IntegerField(blank=True, null=True)),
                ('line_item_index', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('pack', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_row', models.TextField(blank=True, null=True)),
                ('gl3_id', models.IntegerField(blank=True, null=True)),
                ('gl3_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'out_line_item_processed',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_code', models.TextField()),
                ('item_description', models.TextField()),
                ('brand', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generated_product_name', models.TextField(blank=True, null=True)),
                ('enhanced_details', models.TextField(blank=True, null=True)),
                ('estimated_expiration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_product_enhanced',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'in_invoice_processing',
            },
        ),
        migrations.CreateModel(
            name='ConsolidatedGL',
            fields=[
                ('consolidated_gl_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl1_id', models.IntegerField(blank=True, null=True)),
                ('gl1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl1_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gl2_id', models.IntegerField(blank=True, null=True)),
                ('gl2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl2_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gl3_id', models.IntegerField(blank=True, null=True)),
                ('gl3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gl3_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'consolidated_gl',
                'unique_together': {('gl3_id',)},
            },
        ),
        migrations.CreateModel(
            name='GLLevel3',
            fields=[
                ('gl3_id', models.AutoField(primary_key=True, serialize=False)),
                ('gl3_name', models.CharField(max_length=100)),
                ('gl3_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('gl2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_level_3', to='invoice.gllevel2')),
            ],
            options={
                'db_table': 'gl_level_3',
                'unique_together': {('gl2', 'gl3_code')},
            },
        ),
    ]
