# Generated by Django 4.2.9 on 2024-07-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedInvoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('in_invoice_processing_id', models.IntegerField()),
                ('s3_object_key', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('account_number', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('invoice_receipt_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_id', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('batched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_invoice_processed',
            },
        ),
    ]
