# Generated by Django 4.2.9 on 2024-08-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedinvoice',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
