# Generated by Django 4.2.9 on 2024-10-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedproduct',
            name='product_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
