# Generated by Django 4.2.9 on 2024-08-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_processedinvoice_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedinvoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
