# Generated by Django 4.2.9 on 2024-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_processedinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedinvoice',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
