# Generated by Django 4.2.9 on 2024-07-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_processedinvoice_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_invoice_processing_id', models.IntegerField(blank=True, null=True)),
                ('s3_object_key', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('invoice_receipt_id', models.TextField(blank=True, null=True)),
                ('expense_document_index', models.IntegerField(blank=True, null=True)),
                ('line_item_index', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_measure', models.TextField(blank=True, null=True)),
                ('pack', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_row', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_line_item_processed',
            },
        ),
    ]
