# Generated by Django 4.2.9 on 2024-09-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_processedinvoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedinvoice',
            name='vendor_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
