# Generated by Django 4.2.9 on 2024-07-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_processedlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlineitem',
            name='line_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
