# Generated by Django 4.2.9 on 2024-07-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_processedlineitem_line_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedGL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_level_1_id', models.IntegerField()),
                ('gl_level_1_name', models.CharField(max_length=100)),
                ('gl_level_2_id', models.IntegerField()),
                ('gl_level_2_name', models.CharField(max_length=100)),
                ('gl_level_3_id', models.IntegerField()),
                ('gl_level_3_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'inventory_app_consolidated_gl',
            },
        ),
    ]
