# Generated by Django 4.2.9 on 2024-07-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_consolidatedgl'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlineitem',
            name='gl3_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedlineitem',
            name='gl3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
