# Generated by Django 4.2.9 on 2024-07-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_processedlineitem_gl3_id_processedlineitem_gl3_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.TextField(unique=True)),
                ('item_description', models.TextField()),
                ('brand', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('generated_product_name', models.TextField(blank=True, null=True)),
                ('enhanced_details', models.TextField(blank=True, null=True)),
                ('estimated_expiration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'out_product_enhanced',
            },
        ),
    ]
